### ISSUE TITLE
New NPM version introduce braking change

### ISSUE THREAD

**Issue by selfrefactor** [jedmao/postcss-nested-props#11]
I use your library for PostCSS-helper and your new version had broken my build. When reverting to @1.1.1 it works as expected. The error I receive is visible at [https://travis-ci.org/selfrefactor/postcss-helper/builds/190351292](https://travis-ci.org/selfrefactor/postcss-helper/builds/190351292 ) 

The content of the error is     `Error: [object Object] is not a PostCSS plugin`

**Comment by jedmao** [comment]
Can you show me your import statement as well as the implemented call? I think I might have an answer for you.

**Comment by selfrefactor** [comment]
They are both the same as you can see below in the snippet. 

```
        let result = await postcss([
          importLib({from: filepath}),
            require("postcss-nesting")({}),
            require('postcss-inherit'),
            require('postcss-if-media'),
           require('postcss-nested-props'),
            require("autoprefixer")({browsers: [options.autoprefixer]}),
        ]).process(cssString)

```

**Comment by Airkro** [comment]
I get this error too when I update postcss 5.2.9

**Comment by epegzz** [comment]
Same here: Update from `1.1.1` to `1.1.2` gave me `Error: [object Object] is not a PostCSS plugin`

**Comment by jedmao** [comment]
Sorry guys. I restored v1.1.1 in version v1.1.4 until I can fully fix the issue. Looks like a compiler issue. Definitely my fault.
