### ISSUE TITLE
Order in postcss.config.js

### ISSUE THREAD

**Issue by infantito** [jedmao/postcss-nested-props#34]
How is the order?
![image](https://user-images.githubusercontent.com/9045302/31237295-254ecae0-a9bc-11e7-9dff-7cef7f6f9852.png)
![image](https://user-images.githubusercontent.com/9045302/31237463-af633ee6-a9bc-11e7-80c1-74af2ec5379b.png)

**Comment by jedmao** [comment]
Best to put it towards the top. My configuration is:
```js
[
        mixins,
        postcssPropertyLookup,
        postcssNestedProps,
]
```
