### ISSUE TITLE
Specifying multiple parameters in nested elements

### ISSUE THREAD

**Issue by snowe2010** [jedmao/postcss-nested-props#7]
I'm trying specify multiple font families, but I'm getting errors.

```
  font: {
    family: 'Raleway', Arial, sans-serif
    weight: 500
  }
```

results in 

```
compiling... [Error: ParseError: C:\Users\Tyler\Dropbox\Tyler\personal\projects\roots\starboardservices_rewrite\assets\css\header.css.styl:37:31
   33|
   34| .links
   35|   background: #fff
   36|   font: {
   37|     family: 'Raleway', Arial, sans-serif
-------------------------------------^
   38|     weight: 500
   39|   }
   40|   text: {

expected ":", got ","
]

Potentially unhandled rejection [36] ParseError: C:\Users\Tyler\Dropbox\Tyler\personal\projects\roots\starboardservices_rewrite\assets\css\header.css.styl:37:31
   33|
   34| .links
   35|   background: #fff
   36|   font: {
   37|     family: 'Raleway', Arial, sans-serif
-------------------------------------^
   38|     weight: 500
   39|   }
   40|   text: {

expected ":", got ","
```

Any clue what I'm doing wrong?

Also, I'm using stylus with postcss processors like Lost and nested props.

**Comment by jedmao** [comment]
Does it work if you un-nest them?

**Comment by snowe2010** [comment]
Yes.

**Comment by jedmao** [comment]
Doesn't appear to be anything wrong w/ your syntax. Do you think you could create [a failing test](https://github.com/jedmao/postcss-nested-props/blob/master/test/plugin.ts) in the form of a PR?

**Comment by snowe2010** [comment]
I will try!

**Comment by jedmao** [comment]
@snowe2010, please confirm this is fixed in version 1.1.1.

**Comment by jedmao** [comment]
@snowe2010, are you still having this issue? The following test works just fine for me:
```js
it('parses multiple parameters in nested elements', () => {
	check(
		`a{font:{family:'Raleway', Arial, sans-serif;\nweight:500}}`,
		`a{font-family:'Raleway', Arial, sans-serif;font-weight:500}`
	);
});
```
Can you try to update the PostCSS parser and see if that fixes it? Try version 5.1.2.

_Note: I do get errors if I don't put the semi-colon in there, which is why I'm a bit suspicious that the PostCSS parser might be actually having an issue._

**Comment by snowe2010** [comment]
I haven't worked on this project in a while, but as soon as I get back to it (which should be soon) I'll test it out again.

**Comment by jedmao** [comment]
This issue is stale. Closing until further notice.
